# Generated by Django 3.2.9 on 2021-11-08 12:19

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da Ong', max_length=100, verbose_name='Nome')),
                ('fantasia', models.CharField(help_text='Nome Fantasia da Ong', max_length=100, verbose_name='Nome Fantasia')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('street', models.CharField(max_length=150, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=250, verbose_name='Complemento')),
                ('district', models.CharField(max_length=150, verbose_name='Bairro')),
                ('city', models.CharField(max_length=150, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('zipCode', models.CharField(max_length=10, verbose_name='CEP')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
