# Generated by Django 3.2.9 on 2021-11-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='bank',
            field=models.CharField(default='', help_text='Conta bancário da Ong', max_length=50, verbose_name='Conta bancário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ong',
            name='pix',
            field=models.CharField(default='', help_text='PIX da Ong', max_length=50, verbose_name='PIX'),
            preserve_default=False,
        ),
    ]
