# Generated by Django 3.2.2 on 2022-05-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0002_auto_20211129_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
