# Generated by Django 3.2.2 on 2022-05-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211116_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='QuemSomos',
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
