# Generated by Django 3.2.9 on 2021-11-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_auto_20211108_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='genre',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Femêa')], max_length=1, verbose_name='Sexo'),
        ),
    ]
