# Generated by Django 3.2.9 on 2021-11-22 22:53

import animal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_alter_pet_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=animal.models.content_file_name, verbose_name='Foto'),
        ),
    ]
