# Generated by Django 3.2.9 on 2021-11-22 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_pet_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='foto',
            new_name='photo',
        ),
    ]
