# Generated by Django 3.2.9 on 2021-11-23 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20211115_1047'),
        ('animal', '0005_rename_foto_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.breed', verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='coat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animal.coat', verbose_name='Pelagem'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animal.color', verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.specie', verbose_name='Espécie'),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.login')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.pet')),
            ],
        ),
    ]
