# Generated by Django 3.2.9 on 2021-11-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_auto_20211123_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='confirm',
            field=models.BooleanField(default=0, help_text='Confirmação de doação', verbose_name='Confirmação'),
        ),
    ]
