# Generated by Django 3.2.9 on 2021-11-09 23:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=imagekit.models.fields.ProcessedImageField(help_text='Imagem do banner da home', upload_to='www/media/banners', verbose_name='Banner'),
        ),
    ]
