# Generated by Django 3.2.9 on 2021-11-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_alter_banner_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='external',
            field=models.BooleanField(default=False, verbose_name='Link externo?'),
        ),
    ]
