# Generated by Django 3.2.9 on 2021-11-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_banner_external'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='external',
        ),
    ]
