# Generated by Django 3.2.9 on 2021-11-11 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quemsomos',
            options={},
        ),
    ]
